version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/modules/plan-2-edge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/messages"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/blockchain-sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/services/auth-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/services/influencer-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/modules/plan-2-edge/terraform"
    schedule:
      interval: "weekly"

